name: Run Website Health Check
on:
  schedule:
    - cron: '0 7 * * *'   # 7am UTC
    - cron: '0 19 * * *'  # 7pm UTC

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install jupyter nbconvert requests beautifulsoup4
      - name: Run notebook
        run: jupyter nbconvert --to notebook --execute "Website_Health_Check.ipynb"
